# Site settings
title: ToyBox
email: gemini2015@hotmail.com
description: "Articles by Chris Cheng."
baseurl: ""
url: "https://blog.icodeten.com"
twitter_username:  Biggemini2015
github_username:  Gemini2015

# Html settings
paginate: 5

# Handling Reading
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Build settings
markdown: kramdown
permalink: pretty


maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex
  fenced_code_blocks: true

kramdown:
    auto_ids:   true
    footnote_nr:    1
    entity_output:  as_char
    toc_levels:    1..6
    smart_quotes:  lsquo,rsquo,ldquo,rdquo
    fenced_code_blocks: true
    input: GFM


gems: [jekyll-paginate]
