# Site settings
title: ToyBox
email: gemini2015@hotmail.com
description: "CC's Blog, collecting all funny and meaningful things."
baseurl: ""
url: "http://blog.icodeten.com"
twitter_username: StillInsideGFW
github_username:  Gemini2015

# Build settings
markdown: kramdown
permalink: pretty
