# Site settings
title: ToyBox
email: gemini2015@hotmail.com
description: "CC's Blog, collecting all funny and meaningful things."
baseurl: ""
url: "http://blog.icodeten.com"
twitter_username: StillInsideGFW
github_username:  Gemini2015

# Handling Reading
encoding: "utf-8" 
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Build settings
markdown: kramdown
permalink: pretty

# My setting
highlighter: pygments

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex
  fenced_code_blocks: true

kramdown:
    auto_ids:   true
    footnote_nr:    1
    entity_output:  as_char
    toc_levels:    1..6
    smart_quotes:  lsquo,rsquo,ldquo,rdquo
    use_coderay:   true
    fenced_code_blocks: true
    input: GFM

    coderay:
        coderay_wrap:              div
        coderay_line_numbers:      inline
        coderay_line_number_start: 1
        coderay_tab_width:         4
        coderay_bold_every:        10
        coderay_css:               style
